# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-03-16 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_class',
            field=models.CharField(choices=[('B', 'B'), ('A', 'A'), ('C', 'C'), ('D', 'D')], default='A', max_length=32),
        ),
    ]
