# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-03-16 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210316_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_class',
            field=models.CharField(choices=[('D', 'D'), ('B', 'B'), ('C', 'C'), ('A', 'A')], default='A', max_length=32),
        ),
    ]
